databaseChangeLog:
  - changeSet:
      id: 3
      author: Mateusz113
      changes:
        - createTable:
            tableName: VISITS
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: start_time
                  type: java.sql.Types.TIMESTAMP_WITH_TIMEZONE
              - column:
                  name: end_time
                  type: java.sql.Types.TIMESTAMP_WITH_TIMEZONE
              - column:
                  name: patient_id
                  type: bigint
                  constraints:
                    foreignKey: true
                    foreignKeyName: fk_visit_patient
                    references: PATIENTS(id)
              - column:
                  name: doctor_id
                  type: bigint
                  constraints:
                    foreignKey: true
                    foreignKeyName: fk_visit_doctor
                    references: DOCTORS(id)